name: Build and Test "File IO" Component

#define when to run this pipeline/workflow
on: 
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop
jobs:
  build_and_test:
    name: Build the source code and run Tests(GoogleTest) # will displayed on github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3          # use the latest version
      - name: Install prerequisites
        run: sudo apt-get install -y cmake build-essential      # install to some cloud or virtual machines
      - name: build the code
        run: |   # means want to write multiple lines
          mkdir build 
          cd build
          cmake ../file_io
          cmake --build .      
      - name: run tests
        run: ./build/lib_ut_tests
